//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int IDShift { get; set; }
        public Nullable<int> IDRoom { get; set; }
        public Nullable<int> IDEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
    }
}
